# Generated by Django 5.2.16 on 2026-07-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(help_text='Format: +4475836648484', max_length=20, unique=True, verbose_name='Mobile Number'),
        ),
    ]
