# Generated by Django 5.2.16 on 2026-07-08 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('is_price_negotiable', models.BooleanField(default=True, verbose_name='Is Price Negotiable?')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status')),
                ('highlight_type', models.CharField(choices=[('none', 'No Highlight'), ('basic', 'Basic Highlight'), ('premium', 'Premium Highlight'), ('featured', 'Featured Highlight')], default='none', max_length=20, verbose_name='Highlight Type')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('whatsapp_clicks', models.PositiveIntegerField(default=0, verbose_name='WhatsApp Clicks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Session Key')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='Is Anonymous?')),
                ('temp_user_data', models.JSONField(blank=True, null=True, verbose_name='Temporary User Data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Creation IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Session Key')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Clicked At')),
                ('success', models.BooleanField(default=True, verbose_name='Success?')),
            ],
            options={
                'verbose_name': 'WhatsApp Click',
                'verbose_name_plural': 'WhatsApp Clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/images/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement Image',
                'verbose_name_plural': 'Advertisement Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Session Key')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Viewed At')),
            ],
            options={
                'verbose_name': 'Advertisement View',
                'verbose_name_plural': 'Advertisement Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon (FontAwesome)')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color (hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card')], max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Transaction ID')),
                ('payment_data', models.JSONField(blank=True, default=dict, verbose_name='Payment Data')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('highlight_type', models.CharField(choices=[('none', 'No Highlight'), ('basic', 'Basic Highlight'), ('premium', 'Premium Highlight'), ('featured', 'Featured Highlight')], max_length=20, verbose_name='Highlight Type')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Duration (days)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Features')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Plan',
                'verbose_name_plural': 'Payment Plans',
                'ordering': ['price'],
            },
        ),
    ]
