# Generated by Django 5.2.17 on 2026-08-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adimage",
            name="api_image_webp",
            field=models.ImageField(
                blank=True, null=True, upload_to="ads/ad_images_webp/"
            ),
        ),
    ]
