# Generated by Django 5.2.16 on 2026-07-08 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.customerprofile'),
        ),
        migrations.AddField(
            model_name='temporaryad',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_ads', to='ads.category'),
        ),
        migrations.AddField(
            model_name='temporaryadimage',
            name='temporary_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_images', to='ads.temporaryad'),
        ),
    ]
