# Generated by Django 5.2.16 on 2026-07-08 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='Advertiser'),
        ),
        migrations.AddField(
            model_name='advertisementclick',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.advertisement', verbose_name='Advertisement'),
        ),
        migrations.AddField(
            model_name='advertisementimage',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.advertisement', verbose_name='Advertisement'),
        ),
        migrations.AddField(
            model_name='advertisementview',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='ads.advertisement', verbose_name='Advertisement'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ads.category', verbose_name='Parent Category'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='ads.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='payment',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ads.advertisement', verbose_name='Advertisement'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.paymentplan', verbose_name='Plan'),
        ),
        migrations.AlterUniqueTogether(
            name='advertisementimage',
            unique_together={('advertisement', 'order')},
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', 'expiration_date'], name='ads_adverti_status_9343fc_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['category', 'status'], name='ads_adverti_categor_4e7261_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['user', 'status'], name='ads_adverti_user_id_a219bb_idx'),
        ),
    ]
