# Generated by Django 5.2.16 on 2026-07-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_category_icon_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Novo'), ('USED', 'Usado'), ('IMPORTED', 'Importado'), ('LOCAL', 'Produzido em São Tomé')], default='NEW', max_length=20, verbose_name='Condição do Produto'),
        ),
    ]
