# Generated by Django 5.2.17 on 2026-08-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(upload_to='ads/ad_images/'),
        ),
        migrations.AlterField(
            model_name='temporaryadimage',
            name='image',
            field=models.ImageField(upload_to='ads/temp_ad_images/'),
        ),
    ]
