# core/serializers.py
from django.contrib.auth import authenticate
from rest_framework import serializers
from rest_framework.exceptions import AuthenticationFailed, ValidationError

from .models import CustomUser


class UserRegistrationSerializer(serializers.ModelSerializer):
    """
    Serializer for user registration. Handles mobile_number, district, and PIN.
    The PIN is write-only and will be generated by the system.
    """
    pin = serializers.CharField(
        write_only=True,
        min_length=4,
        max_length=4,
        required=True,
        help_text="4-digit system-generated PIN"
    )
    
    class Meta:
        model = CustomUser
        fields = ['id', 'mobile_number', 'district', 'pin']
        extra_kwargs = {
            'mobile_number': {'required': True},
            'district': {'required': True},
        }
    
    def validate_mobile_number(self, value):
        """
        Validate that the mobile number is unique.
        """
        if CustomUser.objects.filter(mobile_number=value).exists():
            raise serializers.ValidationError("A user with this mobile number already exists.")
        return value
    
    def validate_pin(self, value):
        """
        Validate that the PIN is exactly 4 digits.
        """
        if not value.isdigit():
            raise serializers.ValidationError("PIN must contain only digits.")
        if len(value) != 4:
            raise serializers.ValidationError("PIN must be exactly 4 digits.")
        return value
    
    def create(self, validated_data):
        """
        Create a new user with the provided data.
        """
        pin = validated_data.pop('pin')
        user = CustomUser.objects.create_user(
            mobile_number=validated_data['mobile_number'],
            district=validated_data['district'],
            pin=pin
        )
        return user


class UserLoginSerializer(serializers.Serializer):
    """
    Serializer for user login. Validates mobile_number and PIN.
    """
    mobile_number = serializers.CharField(required=True)
    pin = serializers.CharField(
        write_only=True,
        required=True,
        min_length=4,
        max_length=4,
        help_text="4-digit PIN"
    )
    
    def validate(self, attrs):
        """
        Validate the login credentials.
        """
        mobile_number = attrs.get('mobile_number')
        pin = attrs.get('pin')
        
        if not mobile_number or not pin:
            raise ValidationError("Both mobile_number and PIN are required.")
        
        # Authenticate the user
        user = authenticate(
            request=self.context.get('request'),
            username=mobile_number,
            password=pin
        )
        
        if not user:
            raise AuthenticationFailed("Invalid mobile number or PIN.")
        
        if not user.is_active:
            raise AuthenticationFailed("User account is disabled.")
        
        attrs['user'] = user
        return attrs


class ChangePinSerializer(serializers.Serializer):
    """
    Serializer for changing a user's PIN.
    """
    old_pin = serializers.CharField(
        write_only=True,
        required=True,
        min_length=4,
        max_length=4,
        help_text="Current 4-digit PIN"
    )
    new_pin = serializers.CharField(
        write_only=True,
        required=True,
        min_length=4,
        max_length=4,
        help_text="New 4-digit PIN"
    )
    
    def validate_old_pin(self, value):
        """
        Validate that the old PIN is provided and is 4 digits.
        """
        if not value.isdigit():
            raise serializers.ValidationError("PIN must contain only digits.")
        if len(value) != 4:
            raise serializers.ValidationError("PIN must be exactly 4 digits.")
        return value
    
    def validate_new_pin(self, value):
        """
        Validate that the new PIN is different from the old PIN and is 4 digits.
        """
        if not value.isdigit():
            raise serializers.ValidationError("PIN must contain only digits.")
        if len(value) != 4:
            raise serializers.ValidationError("PIN must be exactly 4 digits.")
        
        # Check if new PIN is different from old PIN (old_pin may not be set yet)
        old_pin = self.initial_data.get('old_pin')
        if old_pin and value == old_pin:
            raise serializers.ValidationError("New PIN must be different from the current PIN.")
        
        return value
    
    def validate(self, attrs):
        """
        Validate that the old PIN matches the user's current PIN.
        """
        user = self.context.get('user')
        if not user:
            raise ValidationError("User not found in context.")
        
        old_pin = attrs.get('old_pin')
        
        # Check if the old PIN is correct
        if not user.check_password(old_pin):
            raise ValidationError({"old_pin": "Current PIN is incorrect."})
        
        return attrs
    
    def save(self, **kwargs):
        """
        Save the new PIN for the user.
        """
        user = self.context.get('user')
        new_pin = self.validated_data['new_pin']
        user.set_password(new_pin)
        user.save()
        return user