import random
import re

from djoser.serializers import (
    UserCreateSerializer,
    UserSerializer,
)
from rest_framework import serializers

from .models import User
from .utils import send_pin_sms


class UserSerializer(UserSerializer):
    class Meta:
        model = User
        fields = [
            "id",
            "first_name",
            "last_name",
            "mobile_number",
            "username",
        ]


class UserCreateSerializer(UserCreateSerializer):
    """
    Serializer for user registration.
    The PIN is automatically generated by the system and sent via SMS.
    """

    class Meta:
        model = User
        fields = ["id", "mobile_number", "district"]

    def validate_mobile_number(self, value):
        """
        Validate that the mobile number is unique and properly formatted.
        Accepts numbers with country code like +4475836648484
        """
        # Clean the mobile number (remove spaces, keep + and digits)
        cleaned = re.sub(r"\s+", "", value)

        # Check if it has a country code (+)
        if not cleaned.startswith("+"):
            raise serializers.ValidationError(
                "Phone number must include country code (e.g., +4475836648484)"
            )

        # Check if it contains only digits after the +
        if not re.match(r"^\+\d{7,15}$", cleaned):
            raise serializers.ValidationError(
                "Invalid phone number format. Use format: +4475836648484"
            )

        # Check if user already exists with this number
        if User.objects.filter(mobile_number=cleaned).exists():
            raise serializers.ValidationError(
                "A user with this mobile number already exists."
            )

        return cleaned

    def generate_pin(self):
        """
        Generate a random 4-digit PIN.
        """
        return "".join(random.choices("0123456789", k=4))

    def create(self, validated_data):
        """
        Create a new user with a system-generated PIN.
        """
        # Generate random 4-digit PIN
        pin = self.generate_pin()
        validated_data["username"] = validated_data["mobile_number"]
        validated_data["password"] = pin
        user = super().create(validated_data)
        print(pin)
        send_pin_sms(validated_data["mobile_number"], pin)
        return user
