# core/serializers.py
import random
import re

from django.contrib.auth import authenticate
from rest_framework import serializers
from rest_framework.exceptions import AuthenticationFailed, ValidationError

from .models import CustomUser


class UserRegistrationSerializer(serializers.ModelSerializer):
    """
    Serializer for user registration.
    The PIN is automatically generated by the system and sent via SMS.
    """
    
    class Meta:
        model = CustomUser
        fields = ['id', 'mobile_number', 'district']
        extra_kwargs = {
            'mobile_number': {'required': True},
            'district': {'required': True},
        }
    
    def validate_mobile_number(self, value):
        """
        Validate that the mobile number is unique and properly formatted.
        Accepts numbers with country code like +4475836648484
        """
        # Clean the mobile number (remove spaces, keep + and digits)
        cleaned = re.sub(r'\s+', '', value)
        
        # Check if it has a country code (+)
        if not cleaned.startswith('+'):
            raise serializers.ValidationError("Phone number must include country code (e.g., +4475836648484)")
        
        # Check if it contains only digits after the +
        if not re.match(r'^\+\d{7,15}$', cleaned):
            raise serializers.ValidationError("Invalid phone number format. Use format: +4475836648484")
        
        # Check if user already exists with this number
        if CustomUser.objects.filter(mobile_number=cleaned).exists():
            raise serializers.ValidationError("A user with this mobile number already exists.")
        
        return cleaned
    
    def generate_pin(self):
        """
        Generate a random 4-digit PIN.
        """
        return ''.join(random.choices('0123456789', k=4))
    
    def create(self, validated_data):
        """
        Create a new user with a system-generated PIN.
        """
        # Generate random 4-digit PIN
        pin = self.generate_pin()
        
        # Create user with the generated PIN
        user = CustomUser.objects.create_user(
            mobile_number=validated_data['mobile_number'],
            district=validated_data['district'],
            pin=pin
        )
        
        # Store the PIN in the instance for SMS sending in the view
        user._generated_pin = pin
        
        return user


class UserLoginSerializer(serializers.Serializer):
    """
    Serializer for user login. Validates mobile_number and PIN.
    Accepts mobile_number with country code (e.g., +4475836648484)
    """
    mobile_number = serializers.CharField(required=True)
    pin = serializers.CharField(
        write_only=True,
        required=True,
        min_length=4,
        max_length=4,
        help_text="4-digit PIN"
    )
    
    def validate_mobile_number(self, value):
        """
        Clean the mobile number for authentication.
        """
        # Remove spaces
        cleaned = re.sub(r'\s+', '', value)
        
        # Ensure it has a country code
        if not cleaned.startswith('+'):
            raise serializers.ValidationError("Phone number must include country code (e.g., +4475836648484)")
        
        return cleaned
    
    def validate_pin(self, value):
        """
        Validate that the PIN is exactly 4 digits.
        """
        if not value.isdigit():
            raise serializers.ValidationError("PIN must contain only digits.")
        if len(value) != 4:
            raise serializers.ValidationError("PIN must be exactly 4 digits.")
        return value
    
    def validate(self, attrs):
        """
        Validate the login credentials.
        """
        mobile_number = attrs.get('mobile_number')
        pin = attrs.get('pin')
        
        if not mobile_number or not pin:
            raise ValidationError("Both mobile_number and PIN are required.")
        
        # Authenticate the user
        user = authenticate(
            request=self.context.get('request'),
            username=mobile_number,
            password=pin
        )
        
        if not user:
            raise AuthenticationFailed("Invalid mobile number or PIN.")
        
        if not user.is_active:
            raise AuthenticationFailed("User account is disabled.")
        
        attrs['user'] = user
        return attrs


class ChangePinSerializer(serializers.Serializer):
    """
    Serializer for changing a user's PIN.
    """
    old_pin = serializers.CharField(
        write_only=True,
        required=True,
        min_length=4,
        max_length=4,
        help_text="Current 4-digit PIN"
    )
    new_pin = serializers.CharField(
        write_only=True,
        required=True,
        min_length=4,
        max_length=4,
        help_text="New 4-digit PIN"
    )
    
    def validate_old_pin(self, value):
        """
        Validate that the old PIN is provided and is 4 digits.
        """
        if not value.isdigit():
            raise serializers.ValidationError("PIN must contain only digits.")
        if len(value) != 4:
            raise serializers.ValidationError("PIN must be exactly 4 digits.")
        return value
    
    def validate_new_pin(self, value):
        """
        Validate that the new PIN is different from the old PIN and is 4 digits.
        """
        if not value.isdigit():
            raise serializers.ValidationError("PIN must contain only digits.")
        if len(value) != 4:
            raise serializers.ValidationError("PIN must be exactly 4 digits.")
        
        # Check if new PIN is different from old PIN (old_pin may not be set yet)
        old_pin = self.initial_data.get('old_pin')
        if old_pin and value == old_pin:
            raise serializers.ValidationError("New PIN must be different from the current PIN.")
        
        return value
    
    def validate(self, attrs):
        """
        Validate that the old PIN matches the user's current PIN.
        """
        user = self.context.get('user')
        if not user:
            raise ValidationError("User not found in context.")
        
        old_pin = attrs.get('old_pin')
        
        # Check if the old PIN is correct
        if not user.check_password(old_pin):
            raise ValidationError({"old_pin": "Current PIN is incorrect."})
        
        return attrs
    
    def save(self, **kwargs):
        """
        Save the new PIN for the user.
        """
        user = self.context.get('user')
        new_pin = self.validated_data['new_pin']
        user.set_password(new_pin)
        user.save()
        return user


class ResendPinSerializer(serializers.Serializer):
    """
    Serializer for resending the PIN to a user.
    """
    mobile_number = serializers.CharField(required=True)
    
    def validate_mobile_number(self, value):
        """
        Validate that the user exists and number is properly formatted.
        """
        # Clean the mobile number
        cleaned = re.sub(r'\s+', '', value)
        
        # Ensure it has a country code
        if not cleaned.startswith('+'):
            raise serializers.ValidationError("Phone number must include country code (e.g., +4475836648484)")
        
        try:
            user = CustomUser.objects.get(mobile_number=cleaned)
        except CustomUser.DoesNotExist:
            raise serializers.ValidationError("User with this mobile number does not exist.")
        
        self.context['user'] = user
        return cleaned
    
    def generate_new_pin(self):
        """
        Generate a new random 4-digit PIN.
        """
        return ''.join(random.choices('0123456789', k=4))
    
    def save(self, **kwargs):
        """
        Generate a new PIN and send it to the user.
        """
        user = self.context['user']
        new_pin = self.generate_new_pin()
        
        # Update user's password with new PIN
        user.set_password(new_pin)
        user.save()
        
        return user, new_pin