# ads/serializers.py
from rest_framework import serializers

from .models import (
    Ad,
    AdImage,
    Category,
    CustomerProfile,
    TemporaryAd,
    TemporaryAdImage,
)


class CustomerProfileSerializer(serializers.ModelSerializer):
    """
    Serializer for CustomerProfile with whatsapp_link as read-only.
    """
    whatsapp_link = serializers.ReadOnlyField()
    mobile_number = serializers.CharField(source='user.mobile_number', read_only=True)
    district = serializers.CharField(source='user.district', read_only=True)
    
    class Meta:
        model = CustomerProfile
        fields = ['id', 'mobile_number', 'district', 'whatsapp_link', 'created_at', 'updated_at']
        read_only_fields = ['id', 'created_at', 'updated_at']


class CategorySerializer(serializers.ModelSerializer):
    """
    Serializer for Category model.
    """
    class Meta:
        model = Category
        fields = ['id', 'name', 'slug', 'description']
        read_only_fields = ['id', 'slug']


class AdImageSerializer(serializers.ModelSerializer):
    """
    Serializer for AdImage model.
    """
    image_url = serializers.SerializerMethodField()
    
    class Meta:
        model = AdImage
        fields = ['id', 'image', 'image_url', 'caption', 'order', 'created_at']
        read_only_fields = ['id', 'created_at']
    
    def get_image_url(self, obj):
        """
        Return the URL of the image.
        """
        request = self.context.get('request')
        if request and obj.image:
            return request.build_absolute_uri(obj.image.url)
        return obj.image.url if obj.image else None


class AdSerializer(serializers.ModelSerializer):
    """
    Serializer for Ad model with nested images.
    """
    images = AdImageSerializer(many=True, read_only=True)
    customer = CustomerProfileSerializer(read_only=True)
    category = CategorySerializer(read_only=True)

    # Read-only fields that are controlled by the system
    status = serializers.CharField(read_only=True)
    is_featured = serializers.BooleanField(read_only=True)
    expires_at = serializers.DateTimeField(read_only=True)
    
    class Meta:
        model = Ad
        fields = [
            'id', 'customer', 'category', 'product_name', 'description', 
            'price', 'status', 'is_featured', 'expires_at', 
            'created_at', 'updated_at', 'images'
        ]
        read_only_fields = ['id', 'created_at', 'updated_at']
    
    def validate(self, attrs):
        """
        Ensure the customer is set from the request user's profile.
        """
        request = self.context.get('request')
        if request and hasattr(request.user, 'profile'):
            attrs['customer'] = request.user.profile
        return attrs
    
    def create(self, validated_data):
        """
        Create a new ad with the customer set from the request.
        """
        # Remove customer from validated_data if present, we'll set it ourselves
        customer = validated_data.pop('customer', None)
        request = self.context.get('request')
        
        if request and hasattr(request.user, 'profile'):
            customer = request.user.profile
        
        if not customer:
            raise serializers.ValidationError("Customer profile is required.")
        
        # Create the ad
        ad = Ad.objects.create(customer=customer, **validated_data)
        return ad


class TemporaryAdImageSerializer(serializers.ModelSerializer):
    """
    Serializer for TemporaryAdImage model.
    """
    image_url = serializers.SerializerMethodField()
    
    class Meta:
        model = TemporaryAdImage
        fields = ['id', 'image', 'image_url', 'caption', 'order', 'created_at']
        read_only_fields = ['id', 'created_at']
    
    def get_image_url(self, obj):
        """
        Return the URL of the temporary image.
        """
        request = self.context.get('request')
        if request and obj.image:
            return request.build_absolute_uri(obj.image.url)
        return obj.image.url if obj.image else None


class TemporaryAdSerializer(serializers.ModelSerializer):
    """
    Serializer for TemporaryAd - guest user flow.
    session_token is read-only and generated server-side.
    """
    temporary_images = TemporaryAdImageSerializer(many=True, read_only=True)
    session_token = serializers.UUIDField(read_only=True)
    
    class Meta:
        model = TemporaryAd
        fields = [
            'id', 'session_token', 'category', 'product_name', 
            'description', 'price', 'temporary_images', 'created_at', 'updated_at'
        ]
        read_only_fields = ['id', 'created_at', 'updated_at']
    
    def create(self, validated_data):
        """
        Create a new temporary ad with a generated session token.
        """
        # session_token will be automatically generated by the model's default
        temporary_ad = TemporaryAd.objects.create(**validated_data)
        return temporary_ad
    
    def update(self, instance, validated_data):
        """
        Update an existing temporary ad.
        """
        for attr, value in validated_data.items():
            setattr(instance, attr, value)
        instance.save()
        return instance


class TemporaryAdTransferSerializer(serializers.Serializer):
    """
    Serializer for transferring a temporary ad to an official ad.
    """
    session_token = serializers.UUIDField(required=True)
    
    def validate_session_token(self, value):
        """
        Validate that the session token exists.
        """
        try:
            temporary_ad = TemporaryAd.objects.get(session_token=value)
            self.context['temporary_ad'] = temporary_ad
        except TemporaryAd.DoesNotExist:
            raise serializers.ValidationError("Invalid session token.")
        return value
    
    def validate(self, attrs):
        """
        Ensure the user has a profile.
        """
        request = self.context.get('request')
        if not request or not hasattr(request.user, 'profile'):
            raise serializers.ValidationError("User profile not found.")
        return attrs
    
    def save(self, **kwargs):
        """
        Transfer the temporary ad to an official ad.
        """
        temporary_ad = self.context['temporary_ad']
        user_profile = self.context['request'].user.profile
        
        # Transfer to official ad
        official_ad = temporary_ad.transfer_to_official_ad(user_profile)
        
        return official_ad